<?php
	# generated by EasyPack
	$_lang = array_merge(
		array (
  'setting_modUtilRestlogLimit' => 'Лимит логов rest',
  'setting_use_modUtilFenom' => 'Использовать с fenom',
  'setting_use_modUtilities' => 'Использовать утилиты',
  'setting_use_modUtilitiesRest' => 'Использовать REST',
  'setting_use_modUtilFrontJs' => 'Использовать утилиты на фронте',
  'setting_modUtilities_py_command' => 'Команда для запуска python',
  'setting_modUtilities_py_command_desc' => 'py.python ...',
  'area_modUtilities' => 'modUtilities',
  'area_modUtilities Фронт' => 'modUtilities Фронт',
  'area_modUtilities Питон' => 'modUtilities Питон',
)
		, $_lang);
	